/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.saaweel;

import java.io.FileWriter;
import java.io.IOException;

/**
 *
 * @author Saúl Díaz
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        NextStep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        NextStep.setText("Avanzar");
        NextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextStepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(NextStep, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(NextStep)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextStepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NextStepActionPerformed

    private static void executeGame(Harry harry, Map m) {
        try {
            FileWriter writer = new FileWriter("src/main/java/com/saaweel/registro.log");

            System.out.println("COMIENZA LA BATALLA");
            writer.write("COMIENZA LA BATALLA\n");
            System.out.println("Turno: 0, salud de Harry: " + harry.getHealth());
            writer.write("Turno: 0, salud de Harry: " + harry.getHealth() + "\n");
            System.out.println(m);
            writer.write(m.toString());

            for (int i = 1; harry.getPosition() != m.getExit(); i++) {
                if (i % 10 == 0) {
                    harry.setHealth(harry.getHealth() - 20);
                }

                if (harry.getHealth() <= 0) {
                    System.out.println("Harry no ha conseguido salir del laberinto :(");
                    writer.write("Harry no ha conseguido salir del laberinto :(");
                    writer.close();
                    return;
                }

                System.out.println("Turno: " + i + ", salud de Harry: " + harry.getHealth());
                writer.write("Turno: " + i + ", salud de Harry: " + harry.getHealth() + "\n");

                harry.move(m);

                m.doAdverses(writer);
                
                System.out.println(m);
                writer.write(m.toString());
            }

            System.out.println("HARRY HA GANADO EL JUEGO :)");
            writer.write("HARRY HA GANADO EL JUEGO :)");
            writer.close();
        } catch (IOException e) {
            System.out.println(e.getMessage());   
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
        
        Map m = new Map(4,4);
        m.addWall(0,4);
        m.addWall(3,7);
        m.addWall(5,6);
        m.addWall(5,9);
        m.addWall(8,9);
        m.addWall(8,12);
        m.addWall(10,11);
        m.addWall(10,14);
        m.addWall(11,15);

        m.addAdverse(new Wind("Viento Norte", 2));
        m.addAdverse(new Wind("Viento Sur", 13));
        m.addAdverse(new Dementor(6));
        m.addAdverse(new Dementor(10));
        
        Harry harry = new Harry(m);
        m.spawnHarry(harry);

        executeGame(harry, m);
        
        /*
        m = new Map(7,5);
        m.addWall(0,5);
        m.addWall(2,3);
        m.addWall(3,8);
        m.addWall(6,7);
        m.addWall(6,11);
        m.addWall(7,12);
        m.addWall(8,13);
        m.addWall(13,14);
        m.addWall(13,18);
        m.addWall(15,16);
        m.addWall(15,20);
        m.addWall(16,17);
        m.addWall(17,22);
        m.addWall(18,19);
        m.addWall(19,20);
        m.addWall(19,24);
        m.addWall(20,25);
        m.addWall(22,23);
        m.addWall(22,27);
        m.addWall(23,24);
        m.addWall(25,30); 
        m.addWall(26,27);
        m.addWall(27,32);
        m.addWall(28,29);
        m.addWall(28,33);

        m.addAdverse(new Wind("Viento Norte", 2));
        m.addAdverse(new Wind("Viento Sur", 32));
        m.addAdverse(new Dementor(10));
        m.addAdverse(new Dementor(21));
        m.addAdverse(new Dementor(26));
        m.addAdverse(new Dementor(19));

        harry = new Harry(m);
        m.spawnHarry(harry);

        executeGame(harry, m);
        */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextStep;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
